version: 0.0
os: linux

files:
  - source: gin_demo
    destination: ~/

hooks:
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: ./codedeploy/validateService.sh
      timeout: 180
      runas: ubuntu